### ISSUE TITLE
Integrate tests

### ISSUE THREAD

**Issue by alexcarpenter** [alexcarpenter/butane-show-hide#1]
Integrate some type of tests

**Comment by alexcarpenter** [comment]
Exploring jest as a test suite on https://github.com/alexcarpenter/butane-show-hide/tree/tests

```bash
butane-show-hide git:tests ❯ npm run test                                                                                                               ⏎ ✹ ✭

> butane-show-hide@1.0.0-alpha.2 test /Users/mighty/personal/butane-show-hide
> jest

 FAIL  ./index.test.js
  ● Test suite failed to run

    /Users/mighty/personal/butane-show-hide/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import 'wicg-inert';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

    > 1 | const ButaneShowHide = require('./index')
      2 |

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
      at Object.<anonymous> (index.test.js:1:113)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.501s
Ran all test suites.
```
